import type { CanonicalRegistrySeedRows, CanonicalSeasonSeedRow, CanonicalShowSeedRow } from "./canonical-seed";

export function buildCanonicalRegistrySeedSql(rows: CanonicalRegistrySeedRows): string {
  return [
    "-- Generated by bun run seed:canonical:sql",
    "-- Non-deleting seed: removed upstream rows are handled by a later canonical publishing workflow.",
    "BEGIN;",
    "",
    buildShowUpsert(rows.shows),
    "",
    buildSeasonUpsert(rows.seasons),
    "",
    "COMMIT;",
    "",
  ].join("\n");
}

function buildShowUpsert(rows: readonly CanonicalShowSeedRow[]): string {
  if (rows.length === 0) return "-- No canonical_show rows.";
  return [
    `INSERT INTO public.canonical_show (${[
      "id",
      "display_title",
      "original_title",
      "languages",
      "countries",
      "genre_tags",
      "external_links",
      "notes",
    ].join(", ")}) VALUES`,
    rows.map(showValues).join(",\n"),
    `ON CONFLICT (id) DO UPDATE SET
  display_title = EXCLUDED.display_title,
  original_title = EXCLUDED.original_title,
  languages = EXCLUDED.languages,
  countries = EXCLUDED.countries,
  genre_tags = EXCLUDED.genre_tags,
  external_links = EXCLUDED.external_links,
  notes = EXCLUDED.notes,
  updated_at_us = public.pgxsinkit_clock_us();`,
  ].join("\n");
}

function buildSeasonUpsert(rows: readonly CanonicalSeasonSeedRow[]): string {
  if (rows.length === 0) return "-- No canonical_season rows.";
  return [
    `INSERT INTO public.canonical_season (${[
      "id",
      "show_id",
      "section",
      "season_label",
      "timing",
      "ended_reason",
      "release_pattern",
      "release_precision",
      "date_confidence",
      "release_window",
      "finale_window",
      "sort_key",
      "episode_count",
      "source_row",
      "organizations",
      "external_links",
      "notes",
    ].join(", ")}) VALUES`,
    rows.map(seasonValues).join(",\n"),
    `ON CONFLICT (id) DO UPDATE SET
  show_id = EXCLUDED.show_id,
  section = EXCLUDED.section,
  season_label = EXCLUDED.season_label,
  timing = EXCLUDED.timing,
  ended_reason = EXCLUDED.ended_reason,
  release_pattern = EXCLUDED.release_pattern,
  release_precision = EXCLUDED.release_precision,
  date_confidence = EXCLUDED.date_confidence,
  release_window = EXCLUDED.release_window,
  finale_window = EXCLUDED.finale_window,
  sort_key = EXCLUDED.sort_key,
  episode_count = EXCLUDED.episode_count,
  source_row = EXCLUDED.source_row,
  organizations = EXCLUDED.organizations,
  external_links = EXCLUDED.external_links,
  notes = EXCLUDED.notes,
  updated_at_us = public.pgxsinkit_clock_us();`,
  ].join("\n");
}

function showValues(row: CanonicalShowSeedRow): string {
  return `(${[
    sqlString(row.id),
    sqlString(row.displayTitle),
    sqlNullableString(row.originalTitle),
    sqlJsonb(row.languages),
    sqlJsonb(row.countries),
    sqlJsonb(row.genreTags),
    sqlJsonb(row.externalLinks),
    sqlNullableString(row.notes),
  ].join(", ")})`;
}

function seasonValues(row: CanonicalSeasonSeedRow): string {
  return `(${[
    sqlString(row.id),
    sqlString(row.showId),
    sqlString(row.section),
    sqlString(row.seasonLabel),
    sqlString(row.timing),
    sqlString(row.endedReason),
    sqlNullableString(row.releasePattern),
    sqlString(row.releasePrecision),
    sqlString(row.dateConfidence),
    sqlNullableJsonb(row.releaseWindow),
    sqlNullableJsonb(row.finaleWindow),
    sqlNullableString(row.sortKey),
    sqlNullableNumber(row.episodeCount),
    String(row.sourceRow),
    sqlJsonb(row.organizations),
    sqlJsonb(row.externalLinks),
    sqlNullableString(row.notes),
  ].join(", ")})`;
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNullableString(value: string | null): string {
  return value == null ? "NULL" : sqlString(value);
}

function sqlNullableNumber(value: number | null): string {
  return value == null ? "NULL" : String(value);
}

function sqlJsonb(value: unknown): string {
  return `${sqlString(JSON.stringify(value))}::jsonb`;
}

function sqlNullableJsonb(value: unknown): string {
  return value == null ? "NULL" : sqlJsonb(value);
}
